### ISSUE TITLE
Can you add these game to the list?

### ISSUE THREAD

**Issue by Gahrsdhrg** [Minibattle/Meta-Quest-Affiliate-Codes#4]
• Dragon Fist: VR Kung Fu
• Taiko Frenzy
• Thrill of the Fight 2

**Comment by Minibattle** [comment]
Added all of them except Thrill of the Fight 2. I don't think meta allows me to add early access games at this time. Please remind me to add it when it comes out of early access.

**Comment by Minibattle** [comment]
It let me add everything requested so all of them are available now, thanks for requesting
