### ISSUE TITLE
Iron rebellion

### ISSUE THREAD

**Issue by LaurenceGough** [Minibattle/Meta-Quest-Affiliate-Codes#7]
Can you provide a link for the Iron rebellion meta game?

https://www.meta.com/en-gb/experiences/iron-rebellion/

Thank you

**Comment by Minibattle** [comment]
Waiting for it too show up on my end then I will add it to the global list. In the meantime you can use the Chrome extension to force the discount if you don't wanna wait.

**Comment by Minibattle** [comment]
It is now added
